# Make sure to check the documentation at https://goreleaser.com
version: 2

env:
  - GIT_URL=https://github.com/huhu415/uaProxy
  - TZ=Asia/Shanghai
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
      - loong64 # 龙芯
      - mips # 32位的大端序MIPS处理器
      - mipsle # 32位的小端序MIPS处理器
      - mips64 # 64位的大端序MIPS处理器
      - mips64le # 64位的小端序MIPS处理器
      - ppc64 # 64位的大端序PowerPC处理器
      - ppc64le # 64位的小端序PowerPC处理器
      - riscv64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X uaProxy/bootstrap.Version={{.Version}}
      - -X uaProxy/bootstrap.BuildDate={{.Date}}
      - -X uaProxy/bootstrap.GitCommit={{.Commit}}

archives:
  - format: tar.gz
    wrap_in_directory: true # wrap the archive in a directory named after the project
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- .Arch }}
    files:
      - LICENSE
      - README.md
      - shell
checksum:
  name_template: "checksums.txt"

# https://goreleaser.com/customization/changelog/
changelog:
  disable: true

# https://goreleaser.com/customization/release
release:
  header: |
    ## 🥳Changes

    - 增加了http to websocket功能

    ```sh
    tar -xzvf uaProxy-linux-xxxxxxx.tar.gz # 解压
    ```

  footer: |
    **[FAQ](assets/FAQ.md)**
